### ISSUE TITLE
Change Color

### ISSUE THREAD

**Issue by LarsStuhlmacher** [wysiwyng/wthud#2]
First i think this is really awesome. Its yet another thing the community came up with that should definitly belong in the base game. Anyways, I noticed that sometimes it can be really difficult to read the stats, because of the color of the font. I like to ask if there is already any way to change color or even add like a border for the letters, change the font to a much more readable one or if you still need to add such a feature?

![image](https://user-images.githubusercontent.com/55381464/112228007-d54f6080-8c30-11eb-99d2-9178d81148e4.png)
![image](https://user-images.githubusercontent.com/55381464/112228058-eb5d2100-8c30-11eb-8589-62e41970496c.png)

**Comment by wysiwyng** [comment]
This is probably a bit late, but check out the C# / .Net version of this project: https://github.com/wysiwyng/wthud2. It has a color picker for the HUD font, sadly I haven't yet found a way to add a nice border like in WT itself. Closing as this repo is obsolete.
